experiment_name: simplecnn_gtsrb
model: simple_cnn
dataset: gtsrb
data_dir: data\GTSRB
input_size: 32
train_runs_dir: train_runs
seed: 42
epochs: 10
batch_size: 128
learning_rate: 0.001
num_workers: 0
early_stopping_patience: 15
